// Build-time Bun plugin. Intercepts loads of `<commandsDir>/index.ts` and
// returns an ES module generated by scanning the directory for `command.ts`
// + `meta.ts` files. An `onResolve` hook short-circuits Bun's filesystem
// resolver so the file does not need to exist on disk.
//
// Used by `cli-framework build` via `Bun.build({ plugins: [...] })`. Dev
// mode does not use this plugin — `dev.ts` scans the filesystem at runtime.

import { existsSync } from "node:fs";
import type { BunPlugin } from "bun";
import { Glob } from "bun";

export interface CommandsPluginOptions {
	/** Absolute path to the commands directory. */
	commandsDir: string;
	/** Optional: filename for the root middleware (default `middleware.ts`). */
	middlewareFile?: string;
}

const NAMESPACE = "cli-commands";

function escapeRegExp(str: string): string {
	return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function createCommandsPlugin(opts: CommandsPluginOptions): BunPlugin {
	const { commandsDir } = opts;
	const middlewareFile = opts.middlewareFile ?? "middleware.ts";
	const virtualPath = `${commandsDir}/index.ts`;
	const resolveFilter = new RegExp(`^${escapeRegExp(virtualPath)}$`);
	const loadFilter = /.*/;

	return {
		name: "cli-commands",
		setup(build) {
			build.onResolve({ filter: resolveFilter }, () => ({
				path: virtualPath,
				namespace: NAMESPACE,
			}));

			build.onLoad({ filter: loadFilter, namespace: NAMESPACE }, () => {
				const commandFiles = Array.from(
					new Glob("**/command.ts").scanSync({
						cwd: commandsDir,
						onlyFiles: true,
					}),
				).sort();
				const metaFiles = Array.from(
					new Glob("**/meta.ts").scanSync({
						cwd: commandsDir,
						onlyFiles: true,
					}),
				).sort();

				const middlewarePath = `${commandsDir}/${middlewareFile}`;
				const hasRootMiddleware = existsSync(middlewarePath);

				const lines: string[] = hasRootMiddleware
					? [`import rootMiddleware from ${JSON.stringify(middlewarePath)};`]
					: [];
				for (const [i, match] of commandFiles.entries()) {
					lines.push(
						`import cmd${i} from ${JSON.stringify(`${commandsDir}/${match}`)};`,
					);
				}
				for (const [i, match] of metaFiles.entries()) {
					lines.push(
						`import meta${i} from ${JSON.stringify(`${commandsDir}/${match}`)};`,
					);
				}

				lines.push("", "export const commands = [");
				for (const [i, match] of commandFiles.entries()) {
					const path = match.split("/").slice(0, -1);
					lines.push(`\t{ path: ${JSON.stringify(path)}, command: cmd${i} },`);
				}
				lines.push("];", "", "export const groups = [");
				for (const [i, match] of metaFiles.entries()) {
					const path = match.split("/").slice(0, -1);
					lines.push(`\t{ path: ${JSON.stringify(path)}, ...meta${i} },`);
				}
				lines.push(
					"];",
					"",
					`export const middleware = ${hasRootMiddleware ? "rootMiddleware" : "undefined"};`,
					"",
				);

				return { contents: lines.join("\n"), loader: "ts" };
			});
		},
	};
}
