export const SESSION_CLEANUP_DELAY_MS = 5000;
export const DEBUG_TERMINAL = process.env.SUPERSET_TERMINAL_DEBUG === "1";
export const CREATE_OR_ATTACH_CONCURRENCY = 3;
export const MAX_SCROLLBACK_BYTES = 500_000;
export const MAX_HISTORY_SCROLLBACK_BYTES = 512 * 1024;
export const MAX_KILLED_SESSION_TOMBSTONES = 1000;
