/**
 * Tests for what counts as CLI bookkeeping rather than something a user typed.
 *
 * This is what stops Recent sessions filling with entries titled
 * "<local-command-caveat>Caveat: ...". Every local slash command writes one of
 * these into its transcript, and GatedSpace's own usage refresh runs one a
 * minute per account — so getting this wrong floods the list fast.
 */
import { describe, expect, test } from "bun:test";
import { isBookkeepingText } from "./claude-sessions";

describe("isBookkeepingText", () => {
	test("the caveat a local command writes is bookkeeping", () => {
		expect(
			isBookkeepingText(
				"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.",
			),
		).toBe(true);
	});

	test("so are the other wrappers a slash command leaves behind", () => {
		expect(isBookkeepingText("<local-command-stdout>...")).toBe(true);
		expect(isBookkeepingText("<command-name>/usage</command-name>")).toBe(true);
		expect(isBookkeepingText("<command-message>usage</command-message>")).toBe(
			true,
		);
		expect(isBookkeepingText("<command-args></command-args>")).toBe(true);
		expect(isBookkeepingText("<system-reminder>note</system-reminder>")).toBe(
			true,
		);
	});

	test("leading whitespace doesn't smuggle one through", () => {
		expect(isBookkeepingText("\n  <local-command-caveat>x")).toBe(true);
	});

	test("empty and whitespace-only carry no title either", () => {
		expect(isBookkeepingText("")).toBe(true);
		expect(isBookkeepingText("   \n ")).toBe(true);
	});

	test("a real prompt is NOT bookkeeping, even a short one", () => {
		expect(isBookkeepingText("fix the sidebar")).toBe(false);
		expect(isBookkeepingText("ok")).toBe(false);
	});

	test("a prompt that merely MENTIONS a wrapper still counts as real", () => {
		// Matching anywhere rather than at the start would hide a genuine
		// question about these tags — which is a question someone debugging this
		// would plausibly ask.
		expect(
			isBookkeepingText("why does <local-command-caveat> show up in titles?"),
		).toBe(false);
	});
});
